version: '3.8'

services:
  mathkong-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mathkong-app
    ports:
      - "3000:4173"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mathkong-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mathkong-network:
    driver: bridge
